apiVersion: v1
kind: Service
metadata:
  name: superm-backend
  labels:
    app: superm-backend
    app-identifier: superm
    managed-by: opsera-gitops
  annotations:
    external-dns.alpha.kubernetes.io/hostname: superm-dev.agents.opsera-labs.com
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: superm-backend

