apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: superm-dev

commonLabels:
  environment: dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: superm-backend
    newName: PLACEHOLDER.dkr.ecr.eu-west-2.amazonaws.com/superm-backend
    newTag: latest

replicas:
  - name: superm-backend
    count: 2

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "true"
    target:
      kind: Deployment
      name: superm-backend

