apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gkorgapp2-base

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: gkorgapp2
  tenant: gkorg2
  managed-by: argocd

images:
  - name: gkorgapp2
    newName: gkorgapp2
    newTag: latest
