apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gkorgapp1-base

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: gkorgapp1
  tenant: gkorg
  managed-by: opsera
