apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: luigi-app-base

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: luigi-app
  app.kubernetes.io/managed-by: argocd
  tenant: luigi
