apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: luigi-app-dev

namespace: luigi-app-dev

resources:
- ../../base
- namespace.yaml

commonLabels:
  environment: dev

patches:
- path: deployment-patch.yaml

configMapGenerator:
- behavior: merge
  literals:
  - FLASK_ENV=development
  - FLASK_DEBUG=false
  name: luigi-app-config

images:
- name: luigi-app
  newName: 792373136340.dkr.ecr.eu-west-2.amazonaws.com/luigi/luigi-app
  newTag: 1bc126c0c2b705c9f4905a970eb0561d93fe6c29
