apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gkorgapp2-dev

namespace: gkorgapp2-dev

resources:
- ../../base

commonLabels:
  environment: dev

# Image configuration - updated by CI/CD pipeline
images:
- name: gkorgapp2
  newName: 792373136340.dkr.ecr.eu-west-2.amazonaws.com/gkorg2/gkorgapp2
  newTag: 1bc126c0c2b705c9f4905a970eb0561d93fe6c29

# Dev environment patches

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "128Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "256Mi"
  target:
    kind: Deployment
    name: gkorgapp2
- patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: gkorgapp2-dev.agents.opsera-labs.com
  target:
    kind: Service
    name: gkorgapp2
